[server]
disable_background_tasks = true

[stop_inactive]
inactive_threshold = 900 # 15 minutes
check_interval = 60      # 1 minute

[remove_obsolete]
obsolete_threshold = 1728000 # 20 days
check_interval = 3600        # 1 hour

[custom_urls]
custom_container_name = "https://custom.example.com/container"
