[server]
dry_run = false  # Set to false to actually perform the actions (beware old containers will be deleted)
disable_background_tasks = false
disable_interface = false # Set to true to disable the home status page and log display

[stop_inactive]
inactive_threshold = 900 # 15 minutes
check_interval = 60      # 1 minute
label = "com.akretion.bootemup.stop_inactive"
exclude_urls = ["/queue_job/.*"]

[remove_obsolete]
obsolete_threshold = 1728000 # 20 days
check_interval = 3600        # 1 hour
label = "com.akretion.bootemup.remove_obsolete"

[urls]
custom_container_name = "https://custom.example.com/container"
"custom_(.+)" = "https://example.com/\\1"
"traefik-template" = "http://localhost:8080"
"(.+)" = "http://\\1.localhost"
